name: Update gh-pages with changes on master

on:
  push:
    branches: 
      - master

jobs:
  merge-changes-from-master:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - name: Merge master
        run: >
          git fetch --depth=1 origin master:master

          git -c user.name='auto commit' -c user.email='noreply@localhost' 
          merge origin/master 
          --allow-unrelated-histories 
          --strategy ours 
          --no-edit 

          git push
